apiVersion: apps/v1
kind: Deployment
metadata:
  name: task10-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task10-app
  template:
    metadata:
      labels:
        app: task10-app
    spec:
      containers:
      - name: task10-app
        image: sudaisj/task10-app:IMAGE_TAG
        ports:
        - containerPort: 80
